[package]
name = "helion"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
crossterm = "0.28.1"
lazy_static = "1.5.0"
ratatui = "0.29.0"
tokio = { version = "1.42.0", features = ["full"] }
trotter = "1.0.2"
tui-scrollview = "0.5.1"
colored = "*"
